name: Prepare NPM tarball

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ ubuntu-latest]
        # os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Setup scripts (yarn install)
      run: npm i
      working-directory: scripts
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Download cache from Azure
      run: node scripts/fetch-azure-artifacts.js
      shell: bash
